# Config file for opioid_hotspot project. 
#   A single place where we can specify if we want to keep intermediate files 
#   (and if so, which ones), years we want to do analysis, location of 
#   processed and intermediate files, etc.

#   You can make your own config (everything inherits from `default` so just
#   change what you want), and then set it as a global in your own computer:
#       `Sys.setenv(R_CONFIG_ACTIVE = "dev")`
#   or you can use config::get(config = "dev"); however, you'll need to set it
#   every time you run the code so the global setting is preferred.

default:
  start_year: 1999                # Year to start (restricted-access data)
  end_year: 2015                  # Year to end (restricted-access data)
  working_data: './data'          # Where to save public data (not restricted)
  private_data: './data_private'  # Data that should not be shared
  mcod_files: './data_restricted' # Path to restricted-access files
  zero_rate: .000001              # Log-linear model so cannot have zero rates
  plot_dir: './plots'             # Where to save plots
  proc_in_parallel: false         # When true, perform calculations in parallel
  keep_working_data: false        # Keep intermediate files
  force_process: false            # Force the raw data to be reprocessed
  num_cores: null                 # Number of cores to use (null = 1/2 cores)
  sig_p_value: .01                # What to consider "significant"
  rate_cuts: [10, 20]             # Upper limits of "low"/"medium" mortality
  apc_cuts: [10, 30]              # Upper limits of "low"/"medium" APC
  min_rate: .75                   # Min mortality rate to include in APC plots

# This config version is for me to debug. Keeps original files so I don't
# need to keep downloading over and over. Consider this for development 
# purposes only.
dev:
  proc_in_parallel: true
  keep_working_data: true
  num_cores: 5
